config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"

  resources :products do
    member do
      get :detail
    end
  end

  resources :users do
    resources :orders do
      member do
        get :add_to_cart
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :products

  serialize :product_array
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :order

  validates :product_code, presence: true, uniqueness: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :kana_name, :postal_code, :address1, :address2, :phone, :authority])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @cart = session[:cart]
    @price = session[:price]
    @quantity = session[:quantity]
    if user_signed_in? && @cart.present?
      @products = []
      @cart.each do |product_number|
        @products << Product.find(product_number)
      end
    end

  end

  def add_to_cart
    session[:cart] ||= []
    session[:price] ||= 0
    session[:quantity] ||= 0

    if user_signed_in?
      product = Product.find(params[:id])
      session[:cart] << product.id
      session[:price] += product.price
      session[:quantity] += 1
    end

    redirect_to action: 'index'
  end

  def create
    unless session[:quantity].zero?
      max = Order.maximum(:cart_id)

      if max.nil?
        max = 0
      end

      cart_id = ( max + 1 )
      @order = Order.new(cart_params(cart_id))

      if @order.save
        reset_session
      end
    end

  end

  def update
  end

  def show
  end


  private
  def cart_params(cart_id)
    params.permit(:user_id).merge(product_array: session[:cart], cart_id: cart_id)
  end

  def reset_session
    # cart, price, quantity を初期化
    session[:cart] = []
    session[:price] = 0
    session[:quantity] = 0
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @campain_products = Product.where(price: 1900).order("RAND()").limit(6)
    @recommend_products = Product.where(price: 980).order("RAND()").limit(6)
  end

  def edit
    @product = Product.new
  end

  def create
    @product = Product.new(new_product_params)
    if @product.save
      redirect_to edit_product_path(current_user) , notice: "商品を登録しました。"
    else
      flash.now[:alert] = "商品が登録できませんでした。"
      render :edit
    end
  end

  def detail
    if user_signed_in?
      @product = Product.find(params[:id])
    else
      redirect_to new_user_session_path
      flash[:alert] = "ちょっとわけあって先ずはユーザー登録を！"
    end
  end

  private
  def new_product_params
    params.require(:product).permit(:image, :name, :product_code, :product_category, :price, :count, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.new
  end

  def show
    @user = User.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(update_params)
      redirect_to root_path, notice: "ユーザー情報を編集しました。"
    else
      flash.now[:alert] = "編集内容に誤りがあります。"
      render :edit
    end
  end


  private
  def update_params
    params.require(:user).permit(:name, :kana_name, :email, :postal_code, :address1, :address2, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title zoec
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = stylesheet_link_tag 'slick.css'
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"}
    = javascript_include_tag 'slick.min.js'
    = javascript_include_tag 'jquery.balloon.js'

    %p.notice
      = notice
    %p.alert
      = alert

    = yield

app/views/orders/index.html.haml
= render partial: "products/nav-bar"
.order-detail__contents
  .order-detail__main_contents-wrapper
    - if @quantity.nil? || @quantity.zero?
      .order-detail__main_contents-empty カートに入っている商品はありません
    - else
      - @products.each do |product|
        .order-detail__main_contents
          .order-detail__main_contents_image
            = link_to image_tag(product.image), detail_product_path(product)
          .order-detail__main_contents__description
            .order-detail__product-name #{product.name}
            .order-detail__product_category #{product.product_category}
            .order-detail__product_code #{product.product_code}
            .order-detail__prduct_price ¥ #{product.price}
            .order-detail__attention 返品・交換対象外商品
  .order-detail__purchase_contents
    .order-detail__purchase_contents__summary
      .order-detail__summary
        %table
          %tr
            %td.title 商品合計
            %td.price ¥ #{@price}
          %tr
            %td.title 送料
            %td.price ¥ 0
          %tr
            %td.title 手数料
            %td.price ¥ 0
        %hr.summary
        %table
          %tr
            %td.title 合計金額
            %td.price_summary ¥ #{@price}
    .order-detail__purchase_contents__description
      = link_to root_path do
        = submit_tag "買い物を続ける", class: "purchase_button"
      = form_tag user_orders_path(current_user), method: "post" do
        = submit_tag "商品を購入する", class: "purchase_button", id: "modal-open"
  .clearfix
.footer


- if @quantity.nil? || @quantity.zero?
  #modal-content
    %p 商品をカートに入れてからでなおしてくるんだな
    = link_to "Topへ戻る", root_path, id: "modal-close", class: "button-link"
- else
  #modal-content
    %p ご注文ありがとうございました！
    = link_to "Topへ戻る", root_path, id: "modal-close", class: "button-link"

app/views/products/_category-list.html.haml
.left__contents_search-method
  .left__contents_product-search-method_field
  .left__contents_product-search-method_title 探す
  .left__contents_product-search-method_list ブランドから探す
  .left__contents_product-search-method_list ショップから探す
  .left__contents_product-search-method_list ランキングから探す
  .left__contents_product-search-method_list コーディネートから探す
  .left__contents_product-search-method_list こだわり条件から探す
.left__contents_product-category-list
  .left__contents_product-category-list_title カテゴリ
  .left__contents_product-category-list_product-name トップス
  .left__contents_product-category-list_product-name ジャケット/アウター
  .left__contents_product-category-list_product-name パンツ
  .left__contents_product-category-list_product-name オールインワン
  .left__contents_product-category-list_product-name スカート
  .left__contents_product-category-list_product-name ワンピース
  .left__contents_product-category-list_product-name スーツ/ネクタイ
  .left__contents_product-category-list_product-name バッグ
  .left__contents_product-category-list_product-name シューズ
  .left__contents_product-category-list_product-name ファッション雑貨
  .left__contents_product-category-list_product-name 財布/小物
  .left__contents_product-category-list_product-name ヘアアクセサリー
  .left__contents_product-category-list_product-name アクセサリー
  .left__contents_product-category-list_product-name アンダーウェア
  .left__contents_product-category-list_product-name レッグウェア
  .left__contents_product-category-list_product-name 帽子
  .left__contents_product-category-list_product-name インテリア
  .left__contents_product-category-list_product-name 食器/キッチン
  .left__contents_product-category-list_product-name 雑貨/ホビー/スポーツ
  .left__contents_product-category-list_product-name コスメ/香水
  .left__contents_product-category-list_product-name 音楽/本・雑誌
  .left__contents_product-category-list_product-name 水着/着物・浴衣
  .left__contents_product-category-list_product-name マタニティ/ベビー
  .left__contents_product-category-list_product-name その他

app/views/products/_nav-bar.html.haml
- if user_signed_in?
  - unless session[:quantity] == nil || session[:quantity] == 0
    .current-cart-quantity
      %p #{session[:quantity]}
.nav__bar
  .site-title
    = link_to 'ZoeC', root_path, class: "site-title"
  - if user_signed_in?
    .logout
      = link_to '', destroy_user_session_path, class: "fa fa-times", method: :delete
    .user-edit
      = link_to '', edit_user_path(current_user), class: "fa fa-address-card-o"
    .user-cart
      = link_to '', user_orders_path(current_user), class: "fa fa-shopping-cart fa-lg"
    - if true #(current_user.authority == 1 )
      .product-edit
        = link_to '', edit_product_path(current_user), class: "fa fa-briefcase"
      .admin-user-edit
        = link_to '', user_path(current_user), class: "fa fa-users"
  - else
    .new-user
      = link_to '', new_user_registration_path, class: "fa fa-user-plus"
    .login
      = link_to '', new_user_session_path, class: "fa fa-sign-in"

app/views/products/_parchace-description.html.haml
.description__contents__delivery-alert
  %p
    この商品は、
    %strong 最短明日の午前中
    までに届けるつもりでいます！
.description__contents__product-name
  商品名：
  = @product.name
.description__contents__product-detail
  %p 商品説明
  = @product.description
  %p 商品No：#{ @product.product_code }
  %p カテゴリー：#{ @product.product_category }
  %p 原産国： アレフガルド
  %p 残り在庫数：#{ @product.count }
.description__contents__parchace-button
  .tmp-price #{ @product.price } 円（税込）
  .tmp-button
    %p カートに入れる

app/views/products/_product-description.html.haml
.description__contents__delivery-alert
  %p
    この商品は、
    %strong 最短明日の午前中
    までに届けるつもりでいます！
.description__contents__product-name
  商品名：
  = @product.name
.description__contents__product-detail
  %p 商品説明
  = @product.description
  %p 商品No：#{ @product.product_code }
  %p カテゴリー：#{ @product.product_category }
  %p 原産国： アレフガルド
  %p 残り在庫数：#{ @product.count }
.description__contents__parchace-button
  .tmp-price #{ @product.price }円 税込
  = form_tag add_to_cart_user_order_path(current_user), method: "get" do
    = submit_tag "カートに入れる", class: "add_cart_button"

app/views/products/_shop-list.html.haml
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'banana.jpeg', class: "right-contents-shop-pop"

app/views/products/detail.html.haml
= render partial: "nav-bar"
.product-detail__contents
  .product-detail__main_contents
    .product-detail__contents_image
      .product-detail__contents_slider
        %ul#detail-slider
          %li
            = image_tag @product.image
          %li
            = image_tag @product.image
          %li
            = image_tag @product.image
          %li
            = image_tag @product.image
          %li
            = image_tag @product.image
        %ul#detail-slider-nav
          %li
            = image_tag @product.image
          %li
            = image_tag @product.image
          %li
            = image_tag @product.image
          %li
            = image_tag @product.image
          %li
            = image_tag @product.image
    .product-detail__contents__description
      .product-detail__contents__item-description
        = render partial: "product-description"
.footer

/ #modal-cart-content
/   %p #{@product.name} をカートに保存しました！
/   = link_to "カートへ", user_orders_path(current_user), class: "button-link"

app/views/products/edit.html.haml
= render partial: "products/nav-bar"
.admin-page
  .admin-page__outer
    .admin-page__prouct-title 商品編集
    .admin-page__inner--wrapper
      .product-select_field
        .product-select_field_wrapper
          / = form_tag(product_path, method: :get) do
          /   .product_search_field_wrapper
          /     = text_field_tag :name, "",class: 'input_search_product_code'
          /   = submit_tag "検索する", class: 'admin-edit-btn'
      .product-edit_field
        = form_for @product do |f|
          .product-edit_field-top
            .product-edit_field-top__image
              .product-edit_field__show-image
                %output#js-show-image-field
              .product-edit_field__show-image-button#js-show-image 商品画像を選択する
              = f.file_field :image, id: "file", style: "display:none", value: ""
            .product-edit_field-top__detail
              .product-edit_field__name
                .product-edit_field__label
                  = f.label :name, value: "商品名"
                = f.text_area :name, class: "input_product_name", value: ""
              .product-edit_field__product-category
                .product-edit_field__label
                  = f.label :product_category, value: "商品カテゴリ"
                = f.select :product_category, [["トップス"], ["ジャケット/アウター"], ["パンツ"], ["オールインワン"], ["スカート"], ["ワンピース"], ["スーツ/ネクタイ"], ["バッグ"], ["シューズ"], ["ファッション雑貨"], ["財布/小物"], ["ヘアアクセサリー"], ["アクセサリー"], ["アンダーウェア"], ["レッグウェア"], ["帽子"], ["インテリア"], ["食器/キッチン"], ["雑貨/ホビー/スポーツ"], ["コスメ/香水"], ["音楽/本・雑誌"], ["水着/着物・浴衣"], ["マタニティ/ベビー"], ["その他"]], {include_blank: true}, {class: "input_product_category"}
              .product-edit_field__product-code
                .product-edit_field__label
                  = f.label :product_code, value: "品番"
                = f.text_area :product_code, class: "input_product_code", value: ""
              .product-edit_field__price
                .product-edit_field__label
                  = f.label :price, value: "価格（税抜）"
                = f.text_area :price, class: "input_product_price", value: ""
              .product-edit_field__count
                .product-edit_field__label
                  = f.label :count, value: "在庫数"
                = f.text_area :count, class: "input_product_count", value: ""
          .product-edit_field-bottom
            = f.label :description, value: "商品説明"
            = f.text_area :description, class: "input_product_description", value: ""
            = f.submit "保 存", class: 'product-edit-btn'

app/views/products/index.html.haml
!!!
%body
  = render partial: "nav-bar"
  .contents
    .main_contents
      .left__contents
        = render partial: "category-list"
      .center__contents
        .center__contents_slider
          %ul#slider
            %li
              = image_tag "img01.jpg"
            %li
              = image_tag "img02.jpg"
            %li
              = image_tag "img03.jpg"
            %li
              = image_tag "img04.jpg"
            %li
              = image_tag "img05.jpg"
            %li
              = image_tag "img06.jpg"
          %ul#slider-nav
            %li
              = image_tag "img01.jpg"
            %li
              = image_tag "img02.jpg"
            %li
              = image_tag "img03.jpg"
            %li
              = image_tag "img04.jpg"
            %li
              = image_tag "img05.jpg"
            %li
              = image_tag "img06.jpg"
        .center__contents_wrapper
          .center__contents_campain
            %h5.center__contents_campain-title campain
            %hr.center__contents_campain-line
            .center__contents_campain__top
              - @campain_products.each do |product|
                .center__contents_campain__top-product
                  = link_to image_tag(product.image), detail_product_path(product)
                  %p.center__contents_campain_product-title
                    = product.name
                  %p.center__contents_campain_product-price
                    #{ product.price } 円 税込 ( 30% up！)
          .center__contents_campain
            %h5.center__contents_campain-title recommend
            %hr.center__contents_campain-line
            .center__contents_campain__top
              - @recommend_products.each do |product|
                .center__contents_campain__top-product
                  = link_to image_tag(product.image), detail_product_path(product)
                  %p.center__contents_campain_product-title
                    = product.name
                  %p.center__contents_campain_product-price
                    #{ product.price } 円  税込
          .center__contents_campain
            %h5.center__contents_campain-title coordinate
            %hr.center__contents_campain-line
            .center__contents_campain__top
              .center__contents_campain__top-product
              .center__contents_campain__top-product
              .center__contents_campain__top-product
              .center__contents_campain__top-product
              .center__contents_campain__top-product
              .center__contents_campain__top-product
      .right__contents
        .right__contents_sale
          = image_tag 'roto.jpeg', class: "right-contents-top-pop"
          .roto-mask
            .roto-caption 非売品
        .right__contents_shop-news-title shop news
        .right__contents_shop-news-list
          = image_tag 'banana.jpeg', class: "right-contents-shop-pop"
          .right__contents_shop-news-detail
            %p.shop-news-detail_title test words
            %p.shop-news-detail_description sale sale sale sale sale sale sale sale sale sale sale sale
        = render partial: "shop-list"
  .footer

app/views/products/show.html.haml
= render partial: "products/nav-bar"
.admin-page
  .admin-page__outer
    .admin-page__prouct-title 商品編集
    .admin-page__inner--wrapper
      .product-select_field
        .product-select_field_wrapper
          / = form_tag(product_path, method: :get) do
          /   .product_search_field_wrapper
          /     = text_field_tag :name, "",class: 'input_search_product_code'
          /   = submit_tag "検索する", class: 'admin-edit-btn'
      .product-edit_field
        = form_for @product do |f|
          .product-edit_field-top
            .product-edit_field-top__image
              .product-edit_field__show-image
                %output#js-show-image-field
              .product-edit_field__show-image-button#js-show-image 商品画像を選択する
              = f.file_field :image, id: "file", style: "display:none", value: ""
            .product-edit_field-top__detail
              .product-edit_field__name
                .product-edit_field__label
                  = f.label :name, value: "商品名"
                = f.text_area :name, class: "input_product_name", value: ""
              .product-edit_field__product-category
                .product-edit_field__label
                  = f.label :product_category, value: "商品カテゴリ"
                = f.select :product_category, [["トップス"], ["ジャケット/アウター"], ["パンツ"], ["オールインワン"], ["スカート"], ["ワンピース"], ["スーツ/ネクタイ"], ["バッグ"], ["シューズ"], ["ファッション雑貨"], ["財布/小物"], ["ヘアアクセサリー"], ["アクセサリー"], ["アンダーウェア"], ["レッグウェア"], ["帽子"], ["インテリア"], ["食器/キッチン"], ["雑貨/ホビー/スポーツ"], ["コスメ/香水"], ["音楽/本・雑誌"], ["水着/着物・浴衣"], ["マタニティ/ベビー"], ["その他"]], {include_blank: true}, {class: "input_product_category"}
              .product-edit_field__product-code
                .product-edit_field__label
                  = f.label :product_code, value: "品番"
                = f.text_area :product_code, class: "input_product_code", value: ""
              .product-edit_field__price
                .product-edit_field__label
                  = f.label :price, value: "価格（税抜）"
                = f.text_area :price, class: "input_product_price", value: ""
              .product-edit_field__count
                .product-edit_field__label
                  = f.label :count, value: "在庫数"
                = f.text_area :count, class: "input_product_count", value: ""
          .product-edit_field-bottom
            = f.label :description, value: "商品説明"
            = f.text_area :description, class: "input_product_description", value: ""
            = f.submit "保 存", class: 'product-edit-btn'

app/views/users/edit.html.haml
= render partial: "products/nav-bar"
#account-page.account-page
  .account-page-wrapper
    %h2.account-page_title 登録内容の編集
    / = render "devise/shared/links"
    .account-page__inner--wrapper
      .account-page__inner--wrapper--input
        = form_for @user, url: { controller: :users, action: :update}, method: :put do |f|
          .input_field_wrapper
            .name_field_label
              = f.label 'お名前'
            .name_field_seimei
              = f.text_field :name, placeholder: "姓  名", class: "input_name_seimei", value: "#{ current_user.name }"
          .input_field_wrapper
            .name_field_label
              = f.label 'お名前（カナ）'
            .name_field_kana_seimei
              = f.text_field :kana_name, placeholder: "セイ  メイ", class: "input_name_kana_seimei", value: "#{ current_user.kana_name }"
          .input_field_wrapper
            .email_field_label
              = f.label 'メールアドレス'
            .email_field
              = f.text_field :email, placeholder: "info@sample.jp", class: "input_email", value: "#{ current_user.email }"
          .input_field_wrapper
            .postal_field_label
              = f.label '郵便番号'
            .postal_field_code
              = f.text_field :postal_code, placeholder: "郵便番号", class: "input_postal_code", value: "#{ current_user.postal_code }"
          .input_field_wrapper
            .address_field_label
              = f.label '住所１'
            .address_field_one
              = f.text_field :address1, placeholder: "市区町村、番地など", class: "input_address_one", value: "#{ current_user.address1 }"
          .input_field_wrapper
            .address_field_label
              = f.label '住所２'
            .address_field_two
              = f.text_field :address2, placeholder: "建物名など（任意）", class: "input_address_two", value: "#{ current_user.address2 }"
          .input_field_wrapper
            .phone_field_label
              = f.label '電話番号'
            .phone_field
              = f.telephone_field :phone, placeholder: "000-0000-0000", class: "input_phone_number", value: "#{ current_user.phone }"
          .input_field_wrapper
            .password_field_label
              = f.label 'パスワード'
            .password_field
              = f.password_field :password, autocomplete: "off", placeholder: "英 数 字（小文字）8 文 字 以 上", class: "input_password"
          .input_field_wrapper
            .password_field_label
              = f.label 'パスワード確認'
            .password_field
              = f.password_field :password_confirmation, autocomplete: "off", placeholder: "確認のため、もう一度パスワードを入力してください", class: "input_password"
          = f.submit "上 記 の 内 容 で 登 録", class: 'registration-btn'

app/views/users/show.html.haml
/ nav-bar 挿入
= render partial: "products/nav-bar"
.admin-page
  .admin-page__outer
    .admin-page__prouct-title 権限編集
    .admin-page__inner--wrapper
      .user-search_field
        = form_for @user, url: { controller: :users, action: :update}, method: :put do |f|
          .admin_user_field_wrapper
            = f.text_field :name, class: "input_admin_user", placeholder: "  ユーザー 検索"
          = f.submit "保 存", class: 'admin-edit-btn'
      .user-list_field
        .user-list_field__search-result
          #search-result 検索結果
        .user-list_field__add-result
          #add-result 追加または削除